// backend/auth-service/shared/constants/errorCodes.js

module.exports = {
  // General errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT_ERROR: "CONFLICT_ERROR",
  NOT_FOUND: "NOT_FOUND",
  BUSINESS_LOGIC_ERROR: "BUSINESS_LOGIC_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",

  // Database specific
  UNIQUE_VIOLATION: "UNIQUE_VIOLATION",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  DB_OPERATION_FAILED: "DB_OPERATION_FAILED",
};
